---
- hosts: node2
  tasks: 
#   - ping: ~
   - name: reboot
#     become: true
     reboot:

#- hosts: node2
#  tasks:
#    - ping: ~
#    - name: reboot
#      become: true
#      reboot:
       # update_cache: yes
